"""Per-domain exemplar prompts for centroid-based semantic routing (Phase 2B).

~12 prompts per domain, 6 domains matching keyword_route()'s buckets. Chosen to
cover intent expressed WITHOUT the whitelisted keywords keyword_route() relies on
(the motivating gap — e.g. coding intent with no coding keyword). Re-run
`uv run python -m app.core.embeddings` after editing to rebuild centroids.json.
"""

EXEMPLARS: dict[str, list[str]] = {
    "coding": [
        "my program keeps crashing on line 40 and I can't figure out why",
        "how do I make this loop run faster",
        "the app throws an exception whenever I click submit",
        "help me refactor this messy nested if statement",
        "what's the best way to store user sessions in a web app",
        "my unit tests pass locally but fail in CI",
        "convert this snippet from one language to another",
        "how do I connect to a Postgres instance from my backend",
        "walk me through setting up authentication for my REST endpoints",
        "why does my recursive call blow the stack",
        "explain what a race condition is and how to avoid one",
        "review this pull request and point out any issues",
    ],
    "math": [
        "if a train leaves at 3pm going 60mph how far in two hours",
        "what's the area under this curve between zero and one",
        "find the roots of x squared minus five x plus six",
        "how many ways can I arrange five books on a shelf",
        "what's the chance of rolling two sixes in a row",
        "reduce this fraction to its simplest form",
        "what is the sum of the first hundred natural numbers",
        "prove that the square root of two is irrational",
        "how do I find the slope of a line between two points",
        "what's the expected value of this dice game",
        "compute the standard deviation of these numbers",
        "how much interest do I earn at five percent over three years",
    ],
    "writing": [
        "help me put together a heartfelt message for my grandmother's birthday",
        "I need a catchy opening line for my newsletter",
        "turn these bullet points into a polished paragraph",
        "make this sound more professional and less casual",
        "give me a short bedtime tale about a brave little fox",
        "help me phrase this rejection so it doesn't sting",
        "come up with a tagline for my coffee shop",
        "expand this outline into a few flowing paragraphs",
        "reword my cover note so it stands out to recruiters",
        "craft a toast for my best friend's wedding",
        "summarize this into a punchy social media caption",
        "help me tell this personal story in a more vivid way",
    ],
    "simple": [
        "hey there",
        "what's the capital of France",
        "how are you doing today",
        "thanks a lot",
        "what time zone is Tokyo in",
        "who painted the Mona Lisa",
        "is it going to rain tomorrow",
        "how do you spell restaurant",
        "what's two plus two",
        "good morning",
        "how tall is Mount Everest",
        "when was the internet invented",
    ],
    "analysis": [
        "weigh the upsides and downsides of remote work for a small team",
        "which of these three vendors should we pick and why",
        "break down what's really driving our customer churn",
        "give me a thorough rundown of the risks in this plan",
        "assess whether it makes sense to buy or rent in this market",
        "walk through the implications of switching to a subscription model",
        "what are the second-order effects of raising our prices",
        "map out the tradeoffs between speed and reliability here",
        "evaluate this business proposal end to end",
        "help me think through the long-term consequences of this decision",
        "dig into why sales dipped last quarter across regions",
        "compare these strategies across cost, risk, and timeline",
    ],
    "general": [
        "tell me something interesting about deep sea creatures",
        "what should I cook for dinner with chicken and rice",
        "recommend a few good hiking trails near the coast",
        "explain how airplanes stay in the air",
        "what are some tips for sleeping better at night",
        "give me ideas for a rainy weekend at home",
        "how does the stock market actually work",
        "what's a good beginner houseplant that's hard to kill",
        "describe what life was like in medieval Europe",
        "how do bees make honey",
        "suggest a playlist mood for a long road trip",
        "what causes the northern lights",
    ],
}
